-- Seed Data for BillNova
-- This file is automatically executed when you run `supabase db reset`
-- It provides a default test user and some initial data so you don't start with an empty dashboard.

-- 1. Create a Test User in Supabase Auth
-- Email: test@example.com
-- Password: password123
INSERT INTO auth.users (
  id,
  instance_id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  recovery_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  created_at,
  updated_at,
  confirmation_token,
  email_change,
  email_change_token_new,
  recovery_token
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '00000000-0000-0000-0000-000000000000',
  'authenticated',
  'authenticated',
  'test@example.com',
  crypt('password123', gen_salt('bf')),
  NOW(),
  NOW(),
  NOW(),
  '{"provider":"email","providers":["email"]}',
  '{"business_name":"Demo Business Inc."}',
  NOW(),
  NOW(),
  '',
  '',
  '',
  ''
) ON CONFLICT (id) DO NOTHING;

-- Note: Inserting the user above will automatically trigger `handle_new_user()` 
-- which creates the `profiles` and `businesses` records.

-- 2. Inject Test Invoices and Clients using a DO block to fetch the auto-generated business ID
DO $$
DECLARE
    v_user_id UUID := '00000000-0000-0000-0000-000000000000';
    v_business_id UUID;
    v_client_id UUID;
    v_invoice_id UUID;
BEGIN
    -- Fetch the business ID that was auto-generated by the trigger
    SELECT id INTO v_business_id FROM public.businesses WHERE owner_id = v_user_id LIMIT 1;
    
    -- Ensure business was found before proceeding
    IF v_business_id IS NOT NULL THEN
        
        -- Insert a sample Client
        INSERT INTO public.clients (business_id, name, email, company, phone)
        VALUES (v_business_id, 'John Doe', 'john@acmecorp.com', 'Acme Corporation', '+2348000000000')
        RETURNING id INTO v_client_id;
        
        -- Insert a sample pending Invoice
        INSERT INTO public.invoices (business_id, client_id, invoice_number, issue_date, due_date, status, notes)
        VALUES (
            v_business_id, 
            v_client_id, 
            'INV-1001', 
            CURRENT_DATE, 
            CURRENT_DATE + INTERVAL '14 days', 
            'pending',
            'Thank you for your business.'
        )
        RETURNING id INTO v_invoice_id;
        
        -- Insert Invoice Items for the pending invoice
        INSERT INTO public.invoice_items (invoice_id, description, quantity, price)
        VALUES 
        (v_invoice_id, 'Website Redesign', 1, 150000.00),
        (v_invoice_id, 'Hosting (1 Year)', 1, 20000.00);

        -- Insert a sample paid Invoice
        INSERT INTO public.invoices (business_id, client_id, invoice_number, issue_date, due_date, status)
        VALUES (
            v_business_id, 
            v_client_id, 
            'INV-1002', 
            CURRENT_DATE - INTERVAL '30 days', 
            CURRENT_DATE - INTERVAL '16 days', 
            'paid'
        )
        RETURNING id INTO v_invoice_id;
        
        -- Insert Invoice Items for the paid invoice
        INSERT INTO public.invoice_items (invoice_id, description, quantity, price)
        VALUES 
        (v_invoice_id, 'Consultation Fee', 2, 25000.00);

    END IF;
END $$;
